### ISSUE TITLE
Archetype for Kafka 0.10.2.0

### ISSUE THREAD

**Issue by simplesteph** [jcustenborder/kafka-connect-archtype#2]
Would be awesome to get this archetype updated for the latest and later kafka versions :)

**Comment by jcustenborder** [comment]
[0.10.2.0-cp1](
https://search.maven.org/#artifactdetails%7Ccom.github.jcustenborder.kafka.connect%7Ckafka-connect-parent%7C0.10.2.0-cp1%7Cpom) is out in maven central. I'll push 0.10.2.1-cp1 soon.

**Comment by simplesteph** [comment]
awesome thanks! Update the readme to provide an up to date list of versions one can hit?
